name: Java Workflow Demo

on: [push]

jobs:
  BuildJava:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: List the files in current directory
        run: ls ${{github.workspace}}
      - name: Verify the Java Version
        run: java --version
      - name: test gradel
        run: gradle
      - name: Build java code
        run: gradle build
      - name: list files  
        run: ls ./build/libs
      
      - name: uploading jar file
        uses: actions/upload-artifact@v2
        with:
          path: ./build/libs/      
      
          
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      run: |
          curl http://localhost:5005
